sudo: required

services:
  - docker

env:
  - RELEASE=1.7.1
  - RELEASE=1.7.1-couchperuser
  - RELEASE=2.1.1
  - RELEASE=dev
  - RELEASE=dev-cluster

script:
  - make build VERSION=$RELEASE ARCH=ppc64le configure_options="--disable-fauxton --disable-docs"
  - make build VERSION=$RELEASE configure_options="--disable-fauxton --disable-docs" && docker run -d -p 5984:5984 couchdb:$RELEASE && sleep 10 && curl http://localhost:5984
